project_id = "fpodibymgxupaxgosjls"

[functions.ngss-tagger]
verify_jwt = false

[functions.canvas-proxy]
verify_jwt = false

[functions.generate-questions]
verify_jwt = false

[functions.suggest-dok-blooms]
verify_jwt = false

[functions.generate-lesson-plans]
verify_jwt = false

[functions.lesson-brainstorm]
verify_jwt = false

[functions.generate-escape-room]
verify_jwt = false

[functions.admin-users]
verify_jwt = false

[functions.standards-tagger]
verify_jwt = false

[functions.generate-key-terms]
verify_jwt = false

[functions.generate-content]
verify_jwt = false